### ISSUE TITLE
License is not approved by either OSI or FSF

### ISSUE THREAD

**Issue by ahangarha** [easysoft/zentaopms#67]
In various places it is said that the ZenTao is an Open Source software. The requirement for a software to be considered as Open Source is to be released under one on OSI approved licenses.

ZenTao hs released under **Z Public License (ZPL)**  which is not listed in either OSI list or FSF. They have ZPL license but it is [The Zope Public License](https://opensource.org/licenses/ZPL-2.0) not "Z Public License".

Though I have read the license content and it looks to be compatible with definition of both OSI and FSF. Please clarify the status of license approval.

-----
References:
- [List of Licenses on GNU(FSF)](https://www.gnu.org/licenses/license-list.html)
- [Approved Licenses by OSI](https://opensource.org/licenses/alphabetical)

**Comment by easysoft** [comment]
Hello，we have submited the zentao public license to osi to review  before.  They think that zpl is a badgeware license.
https://opensource.org/minutes20170111 

We think the defination of open source should be changed since the times changed. Fox example many database software companies changed their license from the OSI approved license to their self license.

So you can use zentao freely under the ZPL license as long as you keep the logo of zentao.

**Comment by ahangarha** [comment]
Oh! I didn't see this condition in the license. So clearly it is niether Free Software nor Open Source.

Then may I ask why you say it is Open Source? Isn't it misleading?

**Comment by easysoft** [comment]
When we submited ZPL to OSI to be approved, there's many different opinion about the defination of open source.  One guy said that different culture may has different defination for open source. We very agree it.

So for the zentao users, they can get the source code freely, can modify it freely to satisfy their need, can publish the modified version to their customers freely.  We just ask the user to keep our zentao logo, Not reasonable? 

Why we draft ZPL just because all the OSI approved licenses don't protect the right of the software author. 
In the early years of free software time and open source software time, the users of open source software or free software are most developers or hackers. They observe the rules of community and devote their modification  to community. But now the users changed  and more and more users break the rules of open source.  That's why mongodb changed their license,  that‘s why Elastic  changed their license.

So we don't want every one to understand what we're doing and why we do so, we're keep updating zentao and provide support for our users. Using zentao or not using zentao, depend on your choice.

**Comment by ahangarha** [comment]
When logo cannot be changed freely, it means there is no freedom in modification. Anyway you can have your arguments as even owners or proprietary software have some. What is clear here is that Open Source has some meaning, as Free Software has. If on your home page you clearly emphasize that when you say Open Source, it is your own definition not based on OSD, then I am fine with it. Once Open Source people thought lets coin a new term and did. Maybe you need to coin a new term for what you intend.

I got to this issue since one person asked me to talk about the software as an Open Source software. I looked at it and got impressed. As my regular habit, I checked the license and noticed it is neither Free Software not Open Source (based on FSF and OSI definition). You clarify that your open source has nothing to do with OSD then it is fine. What is happening in practice is that calling ZenTao as an Open Source software is very much misleading which I hope is not intended.

**Comment by easysoft** [comment]
In early years we released zentao under LGPL license.  But many users download our zentao and modify it and then change the logo to their and make money from it. So please let me know which license can help us from those harm?  We're a team, a company, we need earn money to pay salaries to our team and we must make it sure to keep updating zentao thus our free users can use it as long as our team exists.

That's why we draft ZPL. I just ask you a few questions:

1. Is there absolute freedom in the world ?  
2. Is there no any limition in the OSI or FSF licenses?  
3. If you're a kindly man, will you remove our logo or change it to your self logo and annouce it to other people that you developed it? So the only one rule has no limition to you. You're freely to use it.
4. Which is more important? Freedom you said or survival?
5. If you care it, using it or not is your freedom. 
6. There will more and more different opinions about open source, we're not the first one and we're not the last one.  That's our freedom too.

The most important thing to us is to do goodness to other people, that's our mission.

**Comment by ahangarha** [comment]
First of all I am not an experienced business owner (I just made a company). I am not a business adviser as well. So I am not in a position to give you (or myself) a guaranteed solution. There are challenges in from of FLOSS solutions in terms of sustainability and we all need to work on this issue. 

See! You have right to make money in any legal way possible. One might have criticism on it but that is your right. I am not going to argue against that. My whole issue is that you call the software Open Source while it is not.

LGPL was a bad choice for such software. It is made to be used for libraries ans packages which can be used in other software not something like ZenTao. AGPL is a better option since it forced other forks to release their code under AGPL, yet it doesn't force to keep logo (or any other part of the program) intact.

Regarding your questions:
1. Doesn't matter. If you don't want to comply with Free Software or Open Source terms, then don't follow. But don't misuse these names falsely.
2. There are limitations. But none of them violate the very definition. For example Copyleft licenses put limitations in order to protect those essential freedoms in future as well. You can do anything with the software as long as you release under compatible licenses.
3. No license allow to to claim to be the sole developer of the whole software. This is what "bad" people do and you know they can still do it even if you release under ZPL. You know they do it even for proprietary software if they can de-compile it.
4. I don't put the two as opposite to each other but for sure I want free software and software freedom to survive. But I admit the challenge.
5. This is a different issue.
6. I am sure about your good will. I am not here to challenge that. If you remove the "Open Source" from the website, then at lease this discussion would be over. We can still have discussion on if ZPL is a good license for developing a software that care bout users' freedom and open-sourceness. I am a fan of SSPL thought it is not approved by FSF or OSI. But the issue is that mongodb no longer call itself a Free/Open Source software. Even on wikipedia it is called a Source Available software. I have supported SSPL in my own capacity as I think that is protecting freedom. It violates Open Source Definition but frankly I don't care about Open Source. I am still waiting to see how FSF would react on SSPL. You release ZenTao under SSPL, I would support it till the time FSF reject it. Yet, even SSPL doesn't protect the logo.

I think the issue here is not about agreement on Open Source meaning. The issue is about development model and sustainability. I think it is a very genuine concern. And I appreciate ZenTao effort to find some way to keep the software as Free and as Open Source as possible. But lets keeps it clear that ZenTao under ZPL is neither Free Software nor Open Source. As mentioned above, I don't believe ZPL can protect ZenTao from those harms you mentioned. Bad people, do bad things in any way. If you can track them violating ZPL, you can track them if they violate even MIT terms. Am I wrong? Even MIT doesn't let people to claim copyright over already copyrighted code. If they claim to be sole developer of the whole software, you can take legal action against them.

I think examples like NextCloud are in front of us and there are things to learn from them. They sell service not software. That way, they are not much worried about NextCloud software (which is under AGPL) but can sustain its development since they are the best and the most reliable team who can develop and maintain the software for their customers. They get paid for the reliable service they provide. I think this would very well work for ZenTao.

I strongly believe we need to have more discussion on such issues in FLOSS events.

**Comment by ahangarha** [comment]
And truly I appreciate your openness towards such discussion. That assures me much more about your good will.

**Comment by easysoft** [comment]
There're man more important things than argue who's right. You can keep your opinion, that's your freedom.
We have more than 1000 stories need to develop. 
So that's it.

**Comment by ahangarha** [comment]
1. Take what ever definition you like. Irrelevant!
2. Take what ever definition you like. Irrelevant!
3. Power is there to be misused. Irrelevant!

So I just repeat this again. Here, we are not discussing if you should release the software as a Free and Open Source one or not. The issue is that you claim that ZenTao is an Open Source software while it is neither approved by OSI nor can fit to the definition by any interpretation.

If you want to say it is okay to lie and mislead because we are in a imperfect world, then I just can say I am sorry. If not, then let's take honest approach. Either release ZenTao under a FLOSS license or don't claim to be Open Source. At this stage, calling ZenTao an Open Source software is a misleading. I hope it is not a deliberate decision. Your approach proves if it is deliberate or not.
