### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [easysoft/zentaopms#69]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by easysoft** [comment]
Hello,

Thank you very much and you can send the issue to my email: chunsheng@easycorp.ltd.

**Comment by amammad** [comment]
hello dears,
did you see the reports?

**Comment by amammad** [comment]
Hey guys
any feedback?😢

**Comment by easysoft** [comment]
Hello, please send the report to chunsheng@easycorp.ltd.
We don't receive any reports yet.
Perhaps the mail list of security@easycorp.ltd providered by Tencent doesn't work and we'll check it.

**Comment by zidingz** [comment]
@easysoft I'll send another email to security@easycorp.ltd - you'll receive it in about an hour. Thanks!

**Comment by amammad** [comment]
hey guys.
did you receive any email?

**Comment by easysoft** [comment]
Hello， we have received the email and we'll check it. Thanks a lot.

**Comment by easysoft** [comment]
Hello,

You can send email to ***@***.*** Thanks a lot.
 
From: Ziding Zhang
Date: 2021-08-11 23:02
To: easysoft/zentaopms
CC: easysoft; Mention
Subject: Re: [easysoft/zentaopms] Trying to get in touch regarding a security issue (#69)
Hey @easysoft,
We've been trying to contact you on ***@***.*** with updates on zentaopms security issues. However, we suspect our emails have been blocked by your Tencent QQ mail server, which has been known to block Western IPs.
Could you kindly provide an alternate email, possibly not hosted by Tencent? This way, we can maintain a clear channel of communication. Happy to assist you through the process. Thank you, and apologies for the hassle.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
